// avantik.js
module.exports = {
	AVANTIK_AGENCY_CODE: "softmobile",
	AVANTIK_ENDPOINT: "http://vair.avantik.io/TikAeroWebAPI_PM/BookingService.asmx?WSDL",
	AVANTIK_FLIGHT_ENDPOINT: "http://vair.avantik.io/FlightsWebservice/FlightsService.asmx?WSDL",
	AVANTIK_USER_ACCOUNT: "softmobile",
	AVANTIK_USER_PASSWORD: "softmobile1234",
	AVANTIK_QUERY_FLIGHT: "006;008",
	SITA_CSV_FILE_PATH: "./temp/",
	AVANTIK_MESSAGE_ROOM: "#william_test_hubot",
	SLACK_FILE_UPLOAD_TOKEN: "xoxp-4861959806-11435105106-15208321431-584424075c",
	SITA_SEND_TIME_SHIFT: 30,
	SITA_SEND_TIME_SHIFE_UNIT: "minute",
	PASSENGER_MANIFEST_QUERY_FREQUENCY: "*/10 * * * *",
	SITA_FILE_CHECK_TIMEOUT_SECOND: 3600,
	MAX_RECORD_COUNT_PER_FILE: 80
}