{  
  "Flights":{  
     "Details":[  
        {  
           "flight_id":[  
              "{6AAC038E-A136-4CA7-9A1A-3F3428E70D9E}"
           ],
           "origin_rcd":[  
              "DMK"
           ],
           "destination_rcd":[  
              "TPE"
           ],
           "first_origin_rcd":[  
              "DMK"
           ],
           "last_destination_rcd":[  
              "TPE"
           ],
           "airline_rcd":[  
              "ZV"
           ],
           "flight_number":[  
              "006"
           ],
           "operating_airline_rcd":[  
              ""
           ],
           "operating_flight_number":[  
              ""
           ],
           "flight_status_rcd":[  
              "ACTIVE"
           ],
           "aircraft_type_rcd":[  
              "321"
           ],
           "matriculation_rcd":[  
              "B22608"
           ],
           "utc_departure_date":[  
              "20151117 00:00:00"
           ],
           "flight_comment":[  
              ""
           ],
           "internal_comment":[  
              ""
           ],
           "transit_points":[  
              ""
           ],
           "departure_date":[  
              "20151117 00:00:00"
           ],
           "utc_departure_date_time":[  
              "20151117 03:50:00"
           ],
           "planned_departure_time":[  
              "1050"
           ],
           "estimated_departure_time":[  
              "0"
           ],
           "actual_departure_time":[  
              "0"
           ],
           "boarding_time":[  
              "1020"
           ],
           "boarding_gate":[  
              ""
           ],
           "irregularity_rcd":[  
              ""
           ],
           "irregularity_comment":[  
              ""
           ],
           "irregularity_name":[  
              ""
           ],
           "flight_check_in_status_rcd":[  
              "OPEN"
           ],
           "arrival_date":[  
              "20151117 00:00:00"
           ],
           "utc_arrival_date_time":[  
              "20151117 07:30:00"
           ],
           "planned_arrival_time":[  
              "1530"
           ],
           "estimated_arrival_time":[  
              "0"
           ],
           "actual_arrival_time":[  
              "0"
           ],
           "arrival_gate":[  
              ""
           ],
           "number_of_stops":[  
              "0"
           ],
           "number_of_legs":[  
              "1"
           ],
           "flight_duration":[  
              "220"
           ]
        }
     ]
  }
}