// avantik.js
module.exports = {
	AVANTIK_AGENCY_CODE: "softmobile",
	AVANTIK_ENDPOINT: "http://vair.avantik.io/TikAeroWebAPI_PM/BookingService.asmx?WSDL",
	AVANTIK_FLIGHT_ENDPOINT: "http://vair.avantik.io/FlightsWebservice/FlightsService.asmx?WSDL",
	AVANTIK_USER_ACCOUNT: "softmobile",
	AVANTIK_USER_PASSWORD: "softmobile1234",
	AVANTIK_QUERY_FLIGHT: "005;006;007;008;009;010",
	SITA_CSV_FILE_PATH: "./temp/",
	AVANTIK_MESSAGE_ROOM: "#general",
	SLACK_FILE_UPLOAD_TOKEN: "xoxp-15817934643-15821033591-15959835232-f65dfd5794",
	SITA_SEND_TIME_SHIFT: 30,
	SITA_SEND_TIME_SHIFE_UNIT: "minute",
	PASSENGER_MANIFEST_QUERY_FREQUENCY: "0 * * * * *",
	SITA_FILE_CHECK_TIMEOUT_SECOND: 3600
}